version: '3'
services:
  web:
    image: node_chat
    build:
      context: ./infrastructure/docker/node/
    volumes: 
      - ./infrastructure/codeDeploy:/app
      - ./infrastructure/bin/start.sh:/start.sh
    ports:
      - "80:3000"
    networks:
      net:
networks:
  net: